variables:
  SONAR_HOST: https://sonarqube-dev.tramontina.cloud
  SONAR_PROJECT_KEY: # <===== insirá a chave do projeto do sonarqube aqui

ci-job:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  variables:
    DOCKER_HOST: tcp://docker-dind:2375
  before_script:
    - apt update
    - apt-get install -y openjdk-17-jre
    - dotnet tool install --global dotnet-coverage
    - dotnet tool install --global dotnet-sonarscanner
    - export PATH="$PATH:$HOME/.dotnet/tools"
  script:
    # <======================== Inclua aqui a inicialização do sonar scanner
    - dotnet build
    - dotnet test --no-restore
    - dotnet-coverage collect "dotnet test --no-restore" -f xml -o "coverage.xml"
    - # <======================== Inclua aqui a finalização do sonar scanner
  tags:
    - treinamento
